import { ColContainer, Container, Page } from "components/Styled";
import WeatherPanel from "components/WeatherPanel";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { SyntheticEvent } from "react";
import styled from "styled-components";

const Home: NextPage = () => {
  const router = useRouter();

  const onClick = (e: SyntheticEvent) => {
    e.preventDefault();
    router.push("create");
  };
  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <ColContainer>
          <WeatherPanel />
        </ColContainer>
      </Page>
    </div>
  );
};

export default Home;
